[database]
host = "localhost"        # Change if DB is hosted elsewhere (e.g., AWS RDS)
port = "3306"             # Usually stays 3306
user = "root"             # Change to your MySQL username
password = "your_db_pwd"  # Change to your MySQL password
database = "secureshare"  # Change to your DB name
[security]
master_key = "your-strong-master-key"
[email]
smtp_server = "smtp.gmail.com"          # Stays as is for Gmail
smtp_port = "587"                       # Stays as is for TLS
username = "secureshare.noreply@gmail.com"  # Your Gmail account
password = "your_app_password"          # App password generated in Google Account
from_name = "SecureShare"               # Friendly display name
from_email = "secureshare.noreply@gmail.com"  # Same as username